# Generated by Django 3.0.6 on 2020-06-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField(max_length=10)),
                ('qant', models.IntegerField(max_length=3)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=15)),
                ('termos', models.BooleanField()),
            ],
        ),
    ]
