# Generated by Django 3.0.6 on 2020-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_de_produto',
            field=models.CharField(choices=[('PM', 'Placa Mãe'), ('PR', 'Processador'), ('FO', 'Fonte'), ('PV', 'Placa de Vídeo'), ('DR', 'Disco Rígido'), ('MR', 'Memória RAM')], default='PM', max_length=2),
        ),
    ]
