# Generated by Django 3.0.6 on 2020-06-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_auto_20200627_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Usuario')),
            ],
        ),
    ]
