# Generated by Django 3.0.6 on 2020-07-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_remove_usuario_termos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='ref_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda.Usuario'),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('sucesso', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Usuario')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='items',
            field=models.ManyToManyField(to='venda.Historico'),
        ),
    ]
