# Generated by Django 3.0.6 on 2020-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_historico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='produto',
        ),
        migrations.AddField(
            model_name='historico',
            name='nome',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
