# Generated by Django 3.0.6 on 2021-04-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0011_auto_20210414_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='imagem',
            field=models.ImageField(default='False', upload_to='historia'),
        ),
    ]
